In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/kaggle/input/resume-dataset-for-resume-ranking-group-10/resume_data.csv")

In [3]:
df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [4]:
# from dateutil import parser
# from datetime import datetime
# from typing import List

# def calculate_experience(start_dates_list: List[List[str]], end_dates_list: List[List[str]]) -> List[float]:
#     """
#     Calculates the total job experience (in years) for each employee.
#     Ignore entries with invalid start/end dates, such as 'N/A' or None.
    
#     :param start_dates_list: List of lists of start dates (strings)
#     :param end_dates_list: List of lists of end dates (strings)
#     :return: List of total job experience in years for each employee
#     """
#     experience_years = []
#     now = datetime.now()

#     for start_dates, end_dates in zip(start_dates_list, end_dates_list):
#         total_days = 0

#         for start_str, end_str in zip(start_dates, end_dates):
#             # Skip invalid or empty entries
#             if start_str in [None, '', 'N/A'] or end_str in [None, '', 'N/A']:
#                 continue

#             try:
#                 start_date = parser.parse(start_str)
#             except Exception:
#                 continue  # Skip unparsable start date

#             # Handle "Current" or open-ended jobs
#             if str(end_str).strip().lower() in ["till date", "current", "ongoing"]:
#                 end_date = now
#             else:
#                 try:
#                     end_date = parser.parse(end_str)
#                 except Exception:
#                     continue  # Skip unparsable end date

#             # Only add if end_date is after start_date
#             if end_date > start_date:
#                 total_days += (end_date - start_date).days

#         experience_years.append(round(total_days / 365.25, 2))  # Leap years considered

#     return experience_years

In [5]:
import ast
from datetime import datetime
from dateutil import parser

df['start_dates'] = df['start_dates'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
df['end_dates'] = df['end_dates'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])

# Function to calculate experience for a single row
def get_total_experience(start_dates, end_dates):
    total_days = 0
    now = datetime.now()

    for start_str, end_str in zip(start_dates, end_dates):
        if start_str in [None, '', 'N/A'] or end_str in [None, '', 'N/A']:
            continue
        try:
            start_date = parser.parse(start_str)
        except:
            continue

        if str(end_str).strip().lower() in ["till date", "current", "ongoing"]:
            end_date = now
        else:
            try:
                end_date = parser.parse(end_str)
            except:
                continue

        if end_date > start_date:
            total_days += (end_date - start_date).days

    return round(total_days / 365.25, 2)

In [6]:
df['job_experience'] = df.apply(lambda row: get_total_experience(row['start_dates'], row['end_dates']), axis=1)

df.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score,job_experience
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000,5.42
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000,5.58
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667,6.83
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000,13.83
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000,17.25

In [7]:
df.columns

Index(['address', 'career_objective', 'skills', 'educational_institution_name',
       'degree_names', 'passing_years', 'educational_results', 'result_types',
       'major_field_of_studies', 'professional_company_names', 'company_urls',
       'start_dates', 'end_dates', 'related_skils_in_job', 'positions',
       'locations', 'responsibilities', 'extra_curricular_activity_types',
       'extra_curricular_organization_names',
       'extra_curricular_organization_links', 'role_positions', 'languages',
       'proficiency_levels', 'certification_providers', 'certification_skills',
       'online_links', 'issue_dates', 'expiry_dates', '﻿job_position_name',
       'educationaL_requirements', 'experiencere_requirement',
       'age_requirement', 'responsibilities.1', 'skills_required',
       'matched_score', 'job_experience'],
      dtype='object')

In [8]:
df = df.drop([
    'address', 'career_objective', 'professional_company_names', 'company_urls', 'start_dates',
    'end_dates', 'positions', 'locations', 'responsibilities', 'extra_curricular_activity_types',
    'extra_curricular_organization_names', 'extra_curricular_organization_links', 'role_positions', 
    'languages', 'proficiency_levels', 'certification_providers', 'online_links', 'issue_dates', 
    'expiry_dates', 'responsibilities.1'
], axis=1)

In [9]:
df.columns

Index(['skills', 'educational_institution_name', 'degree_names',
       'passing_years', 'educational_results', 'result_types',
       'major_field_of_studies', 'related_skils_in_job',
       'certification_skills', '﻿job_position_name',
       'educationaL_requirements', 'experiencere_requirement',
       'age_requirement', 'skills_required', 'matched_score',
       'job_experience'],
      dtype='object')

In [10]:
# Flatten the list of degrees
all_degrees = df['degree_names'].dropna().explode()

unique_degrees = all_degrees.unique()

unique_degrees = sorted(unique_degrees)

print(unique_degrees)

['["Associate\'s degree", \'Bachelor of Science\']', '["Bachelor\'s degree"]', '["Master\'s in Business Administration (International Business)", "Bachelor\'s in Business Administration Finance", \'Diploma in Business Administration\', None]', '["Master\'s in Finance", \'Bachelor of Science\']', '["Master\'s", \'BBA\']', '["Master\'s", \'Bachelor of Technology\']', "['A.A.', 'Diploma']", "['A.A.S']", "['AAS', 'BA', 'Diploma']", "['ACCA II Part Qualified', 'Diploma', 'Grade 12 (School Certificate)', None]", "['Applied Industrial Ergonomics', 'Lean Certification (Parker Lean Boot Camp I, II, and III)', 'EPA Certification', 'AWS Brazing Certification', 'Six Sigma Academy Greenbelt Training', 'Duggan and Associates Value Stream Mapping', 'Mixed Model Value Stream Mapping', 'Poke-a-Yoke Certification', 'Skills']", "['Associate Degree', 'Bachelor of Science degree']", "['Associate Degree']", "['Associate of Applied Science']", "['Associate of Arts']", "['Associate of Science Degree', 'Bachelor of Science Degree']", "['Associate of Science', 'Associate Degree']", "['Associate of Science', 'Principles of Management']", "['Associate', 'N/A']", "['Associates Degree', 'High School Diploma']", "['Associates', 'Associates']", "['B. Tech']", "['B.A (Economics)', 'M.A (Economics), Correspondence/Distance Learning']", "['B.A (Economics)', 'MSc (Economics)']", "['B.A']", "['B.BA']", "['B.CA', 'M.CA']", "['B.CA']", "['B.Com', 'MBA']", "['B.Com', 'MSc']", "['B.Com', 'PG Diploma']", "['B.E']", "['B.E. (Computers)']", "['B.E. (Data Engineering)']", "['B.S', 'B.S']", "['B.S', 'M.S', 'B.S.I.T']", "['B.S']", "['B.S. Degree', None]", "['B.S. in Computer Science']", "['B.S.']", "['B.Sc (Computer Science Engineering)', 'M.Sc (Data Science)']", "['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']", "['B.Sc', 'M.Sc']", "['B.Sc', 'MCA']", "['B.Sc']", "['B.Sc(CA)']", "['B.TECH']", "['B.TECH(COMPUTERS)']", "['B.Tech & M.Tech(Integrated)']", "['B.Tech (Civil)']", "['B.Tech (Mechanical)']", '[\'B.Tech\', "Master\'s Diploma"]', "['B.Tech', 'Diploma']", "['B.Tech', 'M.E']", "['B.Tech', 'M.Tech']", "['B.Tech', 'MBa']", "['B.Tech', 'MS']", "['B.Tech', 'MSc']", "['B.Tech', 'PG Diploma']", "['B.Tech', 'Post Graduation']", "['B.Tech']", "['B.Tech(Computers)', 'Masters (Data Science)']", "['B.Tech(Computers)']", "['B.Tech(IT)']", "['B.Tech. (Electrical Engineering Specialization in Computer Science)', 'XII', 'X']", "['B.Tech/B.E.']", "['B.tech']", "['BBA', 'BBA', 'MBA']", "['BBA', 'Course', 'High School Diploma', 'Seminar', 'Seminar', 'Seminar']", "['BBA', 'MBA']", "['BBA']", "['BCA', 'MCA']", "['BCA']", "['BS', 'AAS']", "['BS', None]", "['BS']", "['BSc', 'MSc']", "['BSc']", "['BSc(CA)', 'MSc(CA)']", "['Bachelor Business Administration']", "['Bachelor Degree', 'Associate Degree']", "['Bachelor of Arts Degree']", "['Bachelor of Arts', 'Association of Business Executive']", "['Bachelor of Arts']", "['Bachelor of Business Administration']", "['Bachelor of Computer Applications', 'Master of Computer Applications']", "['Bachelor of Engineering (B.E']", "['Bachelor of Engineering']", "['Bachelor of Science /Arts']", "['Bachelor of Science Degree']", "['Bachelor of Science', 'A.S']", "['Bachelor of Science', 'Associate of Arts and Applied Science']", "['Bachelor of Science', 'Associate']", "['Bachelor of Science', 'Bachelor of Science']", "['Bachelor of Science', 'Diploma']", "['Bachelor of Science', 'N/A']", "['Bachelor of Science']", "['Bachelor of Sciences']", "['Bachelor']", "['Bachelors of Arts']", "['Bachelors', 'Associates Degree']", "['Bsc (IT)']", "['Business Administration']", "['Business Certification', 'International Business']", "['Certificate of Completion', 'Select One', 'NEEC Building Operator Certification', 'High School Diploma']", "['Certified Professional Coach', 'Bachelor of Science']", "['Computer Applications Specialist Certificate Program']", "['Course Revisions for the: National Electrical Code', 'Associate Degree']", "['Diploma', 'Bachelor of Science']", "['Diploma', 'N/A', 'N/A', 'N/A', 'N/A']", "['Diploma', None]", "['Diploma']", "['Doctor of Business Administration Management (D.B.A', 'Master of Business Administration (M.B.A', 'B. S. Computer Science']", "['Doctor of Philosophy', 'Master of Science']", "['Dual Degree (B.tech + M.Tech)(Chemical)']", "['ESOL Program', 'Bachelor of Science', 'Associate of Science']", "['Food Handler Certificate', 'High School Diploma', 'N/A']", "['GED', 'A-651-0118, Engineering Common Core', 'A-651-0120, Engineering Mechanical', 'A-652-0298, Gas Turbine Mechanical/Electrical A School', 'A-651-0119, Engineering Electrical', 'A-652-0240, SHIPBD GAGE CAL', 'A-495-0018, SHIPBOARD FIREFIGHTING', 'A-652-0188, Waste Heat Boilers', 'A-012-0077, Class Facilitator Instructional Delivery Continuum', 'G-651-0613, MACHINERY CONTROL SYSTEM', 'J-500-0029, Marine Maintenance And Ship Repair 3-M System Coordinator/Inspector']", "['General Courses', 'Technical Diploma']", "['Graduate Certificate', 'MBA', 'Bachelor of Science']", "['High School Diploma', 'Bachelor of Science, BE Bachelor of Engineering (Honours) (Aerospace)']", "['High School Diploma', None]", "['High School Diploma']", "['Honours Bachelor of Science']", "['Integrated B.E. and M.Sc Hons.']", "['Integrated B.Tech & M.Tech']", "['M.B.A', 'B.A']", "['M.Com (Master of Commerce)', 'B.Com (Bachelor of Commerce)']", "['M.S', 'B.E']", "['M.S.', 'B.S.']", "['M.Tech', 'B.E', 'Course']", "['MBA', 'B.Com', 'Diploma']", "['MBA', 'BBA - Accounting', 'BBA - Finance']", "['MBA', 'BBA']", "['MBA', 'Bachelor of Science', 'Associate of Science']", "['MBA', 'N/A']", '[\'MCA\', "Bachelor\'s Degree in Science"]', "['MEng Computer Science', 'A Level']", "['MSc', 'BA (Honors)']", "['Marketing Management Real Estate']", "['Master degree', 'N/A']", "['Master of Accountancy', 'Bachelor of Accountancy Degree', 'Bachelor of Accountancy', 'Certificate of Business Administration']", "['Master of Arts', 'Bachelor of Arts', 'Associates of Applied Science']", "['Master of Business Administration', 'Bachelor of Science', 'Manufacturing Engineering Technology']", "['Master of Business Administration', 'Bachelor of Science', 'Project Management Graduate Certificate']", "['Master of Business Administration', 'Bachelor of Science']", "['Master of Business', 'Bachelor of Commerce']", "['Master of Computer Applications (MCA)', 'Bachelors of Science']", "['Master of Science Degree', 'Bachelor of Science']", "['Master of Science', 'Bachelor of Arts']", "['Master of Science', 'Bachelor of Engineering']", "['Master of Science', 'Bachelor of Science', 'Bachelor of Science']", "['Master of Science', 'Bachelor of Science']", "['Master of Science', 'Bachelor of Technology']", "['Master of Science', 'M. Eng', 'Bachelor of Science']", "['Master of Science', 'Master of Science', 'Bachelor of Science']", "['Master', 'Bachelor of Science', None]", "['Masters of Business Administration', 'Attending', 'Bachelor of Science', 'Associate of Science']", "['Masters of Business Administration', 'Bachelor of Science']", "['Masters of Business Administration', 'Bachelors of Science', 'N/A']", "['Masters of Public Administration', 'B.A. General Studies', 'High School Diploma']", '[\'Masters of Science in Information Technology\', "Bachelor\'s Degree in Computer Science", \'Certification in computer packages\', \'KCSE\', \'KCPE\']', "['Masters of Science', 'BBA']", "['Masters of Science', 'Bachelor of Engineering']", "['Masters', 'Bachelor', 'Associate of Arts']", "['Mechanical-Industrial Engineering', 'Executive Management', 'Business Development']", "['Minor', 'Testing Computer Software', 'BS']", "['N/A', 'B.E', 'Class XII']", "['N/A', 'High School Diploma']", "['N/A', 'N/A']", "['Ph. D', 'M. S', 'B. S']", "['Ph.D. in Computer Science', 'Master in Computer Science', 'Bachelor in Physics']", "['Ph.D.', 'M.S.']", "['Ph.D.', 'Master of Science', 'Bachelor of Arts']", "['PhD Candidate, Computer Science', 'B.Sc., Double major in Computer Science and Management']", "['PhD in Computer Science', 'Hauptdiplom (equivalent to MSc) in Computer Science', 'Vordiplom (comparable to BSc) in Commercial Information Technology', 'Vordiplom (comparable to BSc) in Computer Science']", "['PhD', 'M.S.', 'B.S.']", "['Pharmacy Technician', 'Executive MBA', 'Bachelor of Arts']", "['Trained as Accountant']", "[None, 'General Diploma']"]

In [11]:
# import ast
# import re

# def extract_degree_levels(degree_raw):
#     # Adding common degrees, certifications, partial degrees, vocational level and other levels, and junk or informal entries
#     degree_levels = ['phd', 'msc', 'm.sc', 'mba', 'bsc', 'b.sc', 'bca', 'mca', 'ba', 'ma', 'be', 'b.e', 'me', 'm.e', 
#                      'bs', 'ms', 'btech', 'mtech', 'associate', 'diploma', 'certificate', 'bachelors', 'masters',
#                      'aa', 'aas', 'as', 'bba', 'mbs', 'pg', 'high school', 'doctorate', "b.eng", "m.eng", "mcom", 
#                      "m.com", "bcom", "b.com", "bba", "mba executive", "b.ed", "m.ed", "b.arch", "m.arch", "b.pharm", 
#                      "m.pharm", "llb", "llm", "md", "mbbs", "dds", "dmd", "dba", "ed.d", "jd", "hnd", "gce a-level", 
#                      "gce o-level", "ged", "acca", "cpa", "lean six sigma", "green belt", "black belt", "certificate",
#                      "bootcamp", "value stream mapping", "aws certification", "epa certification", "vocational",
#                      "trade school", "technical diploma", "community college", "training program",
#                      "professional development", "dual degree", "honours", "honors", "distance learning", 
#                      "correspondence", "continuing education", "n/a", "none", "course", "general courses", "attending", 
#                      "unknown", "not specified", "incomplete", "present", "still studying"]

#     # Clean up the input to make sure it's in list form
#     try:
#         # If it's a string that looks like a list, parse it
#         if isinstance(degree_raw, str) and degree_raw.strip().startswith("["):
#             degree_list = ast.literal_eval(degree_raw)
#         elif isinstance(degree_raw, list):
#             degree_list = degree_raw
#         else:
#             degree_list = [degree_raw]
#     except:
#         degree_list = [degree_raw]  # Fallback in case parsing fails

#     cleaned_levels = set()
#     for degree in degree_list:
#         if not isinstance(degree, str):
#             continue

#         # Lowercase and remove punctuations like dots, commas etc.
#         text = re.sub(r'[^\w\s]', '', degree.lower())
        
#         # Tokenize
#         words = text.split()

#         # Match against known degree levels
#         for word in words:
#             if word in degree_levels:
#                 cleaned_levels.add(word)

#     return list(cleaned_levels) if cleaned_levels else None

In [12]:
# Second method (using aliases)

import re

# Mapping canonical degree to various common forms
# EDUCATION_ALIASES = {
#     "phd": ["doctor of philosophy", "ph.d", "doctorate"],
#     "mba": ["master of business administration", "mba executive"],
#     "bsc": ["bachelor of science", "b.sc", "b.s"],
#     "msc": ["master of science", "m.sc", "m.s"],
#     "ba": ["bachelor of arts"],
#     "ma": ["master of arts"],
#     "bcom": ["bachelor of commerce", "b.com"],
#     "mcom": ["master of commerce", "m.com"],
#     "be": ["bachelor of engineering", "b.e", "b.eng"],
#     "me": ["master of engineering", "m.e", "m.eng"],
#     "bba": ["bachelor of business administration"],
#     "mtech": ["master of technology"],
#     "btech": ["bachelor of technology"],
#     "diploma": ["technical diploma", "associate diploma", "polytechnic diploma"],
#     "high school": ["high school diploma", "gce o-level", "ged", "gce a-level"],
# }
EDUCATION_ALIASES = {
    "phd": ["doctor of philosophy", "ph.d", "ph.d.", "phd", "doctorate", "ph.d. in", "phd candidate"],
    "mba": ["master of business administration", "mba executive", "executive mba", "mba", "masters of business administration"],
    "msc": ["master of science", "m.sc", "m.s", "masters of science", "msc", "masters in science", "m.sc."],
    "ma": ["master of arts", "m.a", "m.a.", "masters of arts"],
    "mcom": ["master of commerce", "m.com", "mcom"],
    "me": ["master of engineering", "m.e", "m.eng", "m.e.", "m.engg"],
    "mtech": ["master of technology", "m.tech", "mtech", "mtech integrated"],
    "bsc": ["bachelor of science", "b.sc", "b.s", "bsc", "b.sc.", "b.s.", "honours bachelor of science", "bachelors of science"],
    "ba": ["bachelor of arts", "b.a", "ba", "b.a.", "bachelors of arts"],
    "bcom": ["bachelor of commerce", "b.com", "bcom"],
    "be": ["bachelor of engineering", "b.e", "b.e.", "b.eng", "b.engg", "bachelor of engineering (b.e"],
    "btech": ["bachelor of technology", "b.tech", "b.tech.", "btech", "b.tech(computers)", "dual degree (b.tech + m.tech)", "integrated b.tech & m.tech"],
    "bba": ["bachelor of business administration", "b.b.a", "bba", "bba - accounting", "bba - finance", "bachelor business administration"],
    "bca": ["bachelor of computer applications", "b.c.a", "bca"],
    "mca": ["master of computer applications", "m.c.a", "mca"],
    "bs": ["bs", "b.s", "b.s.", "b.s in", "bachelor's degree in science", "bachelor's in science"],
    "ms": ["ms", "m.s", "m.s.", "master in computer science", "masters of science in information technology"],
    "aa": ["associate of arts", "a.a", "aa"],
    "aas": ["associate of applied science", "a.a.s", "aas"],
    "as": ["associate of science", "a.s", "as", "associate of science degree"],
    "associate": ["associate's degree", "associate degree", "associates degree", "associates", "associate"],
    "diploma": ["technical diploma", "associate diploma", "polytechnic diploma", "diploma", "general diploma", "pg diploma", "master's diploma"],
    "high school": ["high school diploma", "ged", "grade 12", "xii", "x", "kcse"],
    "certificate": ["certificate of completion", "graduate certificate", "business certification", "epa certification", "aws brazing certification", "skills", "course", "certification", "minor", "training", "coaching"],
    "others": ["n/a", "select one", "attending", "testing computer software", "general courses"],

    # Education levels that are more common in the Sri Lankan context
    "al": ["advanced level", "a/l", "a.l", "gce a/l", "gce advanced level", "gce (a/l)", "gce(al)", "gce-a/l"],
    "ol": ["ordinary level", "o/l", "o.l", "gce o/l", "gce ordinary level", "gce (o/l)", "gce(ol)", "gce-o/l"],
    "nvq": ["nvq", "nvq level 3", "nvq level 4", "nvq level 5", "nvq level 6", "national vocational qualification", "nvq diploma"],
    "hnd": ["hnd", "higher national diploma", "hnd in", "higher national diploma in"],
    "cima": ["cima", "chartered institute of management accountants", "cima qualification"],
    "acca": ["acca", "association of chartered certified accountants"],
    "ca": ["chartered accountant", "institute of chartered accountants of sri lanka", "ica", "ca sri lanka"],
    "slim": ["slim", "slim diploma", "sri lanka institute of marketing", "slim pgd"],
    "nibt": ["nibt", "national institute of business & technology", "nibt diploma"],
    "bit": ["bit", "bachelor of information technology", "bit degree", "bit (colombo university)"]

}

# Ranking the levels (higher number = higher qualification)
# EDUCATION_RANKS = {
#     "high school": 0,
#     "diploma": 2,
#     "bsc": 3,
#     "ba": 3,
#     "be": 3,
#     "bcom": 3,
#     "bba": 3,
#     "btech": 3,
#     "msc": 4,
#     "ma": 4,
#     "mba": 4,
#     "mtech": 4,
#     "me": 4,
#     "phd": 5
# }
EDUCATION_RANKS = {
    "others": 0,
    
    "high school": 1,
    "certificate": 1,
    "ol": 1,
    
    "al": 2,
    
    "diploma": 3,
    "associate": 3,
    "nvq": 3,
    "hnd": 3,
    "aa": 3,
    "aas": 3,
    "as": 3,
    "slim": 3,  
    "nibt": 3,   
    
    "bsc": 4,
    "bs": 4,
    "ba": 4,
    "be": 4,
    "btech": 4,
    "bit": 4,    
    "cima": 4,   
    "acca": 4,      
    "bcom": 4,
    "bba": 4,
    "bca": 4,
    
    "msc": 5,
    "ms": 5,
    "ma": 5,
    "me": 5,
    "mtech": 5,
    "mcom": 5,
    "mba": 5,
    "mca": 5,
    "ca": 5,
    
    "phd": 6
}

# Flattenning the aliases for easy reverse lookup
FLATTENED_ALIASES = {}
for canonical, synonyms in EDUCATION_ALIASES.items():
    for synonym in synonyms:
        FLATTENED_ALIASES[synonym.lower()] = canonical


def get_highest_education(degree_entries):
    if not isinstance(degree_entries, list):
        degree_entries = [degree_entries]

    best_match = ("unknown", -1)

    for entry in degree_entries:
        if not isinstance(entry, str):
            continue

        # Clean and normalize text
        text = re.sub(r'[^\w\s]', '', entry.lower())

        # Try matching from aliases
        for synonym, canonical in FLATTENED_ALIASES.items():
            if synonym in text:
                rank = EDUCATION_RANKS.get(canonical, -1)
                if rank > best_match[1]:
                    best_match = (canonical, rank)

        # Fallback to direct canonical keyword matching
        for canonical, rank in EDUCATION_RANKS.items():
            if canonical in text:
                if rank > best_match[1]:
                    best_match = (canonical, rank)

    return best_match[1]

In [13]:
df['highest_degree'] = df['degree_names'].apply(get_highest_education)

In [14]:
all_highest_degree = df['highest_degree'].dropna().explode()

unique_highest_degree = all_highest_degree.unique()

# unique_degrees = sorted(unique_degrees)

print(unique_highest_degree)

[ 4  5 -1  6  3]

In [15]:
num_nan_values = df['degree_names'].isna().sum()
print("Number of NaN values in degree_names:", num_nan_values)

num_nan_values1 = df['highest_degree'].isna().sum()
print("Number of NaN values in highest_degree:", num_nan_values1)

Number of NaN values in degree_names: 84
Number of NaN values in highest_degree: 0

In [16]:
degree_counts = df["highest_degree"].value_counts()

print(degree_counts)

highest_degree
 4    4976
 5    3858
 3     290
-1     224
 6     196
Name: count, dtype: int64